#!/usr/bin/env python3
"""Build a checked, version-pinned runtime, then activate with rollback.
No project registry or credentials are regenerated by setup.
"""
from pathlib import Path
import argparse
import fcntl
import json
import os
import shutil
import subprocess
import tempfile
import time
import manage
import permissions

APP_ROOT = Path(__file__).resolve().parents[2]
ROOT = manage.ROOT
EXPECTED = {'@wonderwhy-er/desktop-commander': '0.2.51', '@modelcontextprotocol/sdk': '1.30.0'}


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError('Unsupported Desktop Commander config layout; runtime not changed.')
    return text.replace(old, new, 1)


def build():
    deps = APP_ROOT / 'node_modules'
    for name, version in EXPECTED.items():
        actual = json.loads((deps / name / 'package.json').read_text())['version']
        if actual != version: raise RuntimeError(f'{name}: expected {version}, found {actual}. Run npm ci at the repository root.')
    stage = Path(tempfile.mkdtemp(prefix='.runtime-stage-', dir=ROOT))
    try:
        dc = deps / '@wonderwhy-er/desktop-commander'
        shutil.copytree(dc / 'dist', stage / 'dc/dist')
        shutil.copy2(dc / 'package.json', stage / 'dc/package.json')
        # Node also walks this parent node_modules for hoisted dependencies.
        (stage / 'node_modules').symlink_to(deps, target_is_directory=True)
        if (dc / 'node_modules').exists(): (stage / 'dc/node_modules').symlink_to(dc / 'node_modules', target_is_directory=True)
        config = stage / 'dc/dist/config.js'
        config.write_text(replace_once(config.read_text(), "const CONFIG_DIR = path.join(USER_HOME, '.claude-server-commander');", "const CONFIG_DIR = process.env.MCP_DC_CONFIG_DIR || path.join(USER_HOME, '.claude-server-commander');"))
        (stage / 'bridge').mkdir()
        (stage / 'auth').mkdir()
        shutil.copy2(APP_ROOT / 'src/bridge/server.mjs', stage / 'bridge/server.mjs')
        shutil.copy2(APP_ROOT / 'src/auth/proxy.cjs', stage / 'auth/proxy.cjs')
        shutil.copy2(APP_ROOT / 'src/bridge/stdio.cjs', stage / 'bridge/stdio.cjs')
        for name in ['policy.cjs', 'approvals.cjs', 'identity.cjs', 'permissions.json']:
            shutil.copy2(APP_ROOT / 'src/bridge' / name, stage / 'bridge' / name)
        for script in ['bridge/server.mjs', 'auth/proxy.cjs', 'bridge/stdio.cjs', 'bridge/policy.cjs', 'bridge/approvals.cjs', 'bridge/identity.cjs', 'dc/dist/config.js']:
            subprocess.run([manage.node_binary(), '--check', str(stage / script)], check=True)
        (stage / 'build.json').write_text(json.dumps({**EXPECTED, 'permissionVersion': 2}, indent=2))
        return stage
    except Exception:
        shutil.rmtree(stage)
        raise


def activate(stage, legacy_permissions=None):
    runtime = ROOT / 'runtime'
    original = manage.load()
    legacy = [p['slug'] for p in original if 'permissions' not in p]
    if legacy and legacy_permissions is None:
        shutil.rmtree(stage)
        raise ValueError('Legacy workspaces require an explicit permission choice: ' + ', '.join(legacy)
                         + '. Run titian runtime update --legacy-permissions readonly (or editor/unrestricted).')
    projects = []
    for old in original:
        p = dict(old)
        p['permissions'] = permissions.validate(p.get('permissions', {'version': 2, 'preset': legacy_permissions or 'readonly', 'rules': {}}))
        p.pop('commandMode', None)
        p.pop('allowedCommands', None)
        projects.append(p)
    active = [p for p in projects if p.get('enabled', True)]
    names = [manage.label(p['slug'], part) for p in active for part in ['bridge', 'auth']]
    running = [name for name in names if manage.loaded(name)]
    backup = ROOT / 'archives' / f'runtime-{time.time_ns()}'
    backup.parent.mkdir(exist_ok=True, mode=0o700)
    # Save registry AND generated environment files, so activation rollback does
    # not pair an old runtime with new policies (or vice versa).
    files = {ROOT / 'projects.json': (ROOT / 'projects.json').read_bytes()}
    for p in projects:
        for part in ['bridge', 'auth']:
            for folder in [ROOT / 'launchagents', manage.AGENTS]:
                file = folder / (manage.label(p['slug'], part) + '.plist')
                files[file] = file.read_bytes() if file.exists() else None
    swapped = False
    try:
        for name in running: manage.stop(name)
        if runtime.exists(): os.replace(runtime, backup)
        try: os.replace(stage, runtime)
        except Exception:
            if backup.exists(): os.replace(backup, runtime)
            raise
        swapped = True
        for p in projects:
            for part in ['bridge', 'auth']:
                name = manage.label(p['slug'], part) + '.plist'
                data = manage.plist_for(p, part)
                manage.atomic(ROOT / 'launchagents' / name, data, 0o644)
                if p.get('enabled', True): manage.atomic(manage.AGENTS / name, data, 0o644)
        manage.save(projects)
        for name in running: manage.launch('bootstrap', manage.DOMAIN, str(manage.AGENTS / (name + '.plist')))
        for p in active:
            if manage.label(p['slug'], 'bridge') in running:
                manage.wait_health(p['bridgePort']); manage.wait_health(p['authPort'])
                permissions.verify_effective(ROOT, p)
    except Exception:
        for name in running: manage.stop(name)
        if swapped:
            failed = ROOT / 'archives' / f'runtime-failed-{time.time_ns()}'
            os.replace(runtime, failed)
            if backup.exists(): os.replace(backup, runtime)
        for file, content in files.items():
            if content is None: file.unlink(missing_ok=True)
            else: manage.atomic(file, content, 0o644)
        for name in running: manage.launch('bootstrap', manage.DOMAIN, str(manage.AGENTS / (name + '.plist')))
        raise
    print('Runtime activated. Permissions verified for restarted services; stopped services remain unverified. Credentials preserved.')


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--install', action='store_true', help='Install a first runtime without starting services')
    mode.add_argument('--activate', action='store_true', help='Restart active project services using the checked runtime')
    parser.add_argument('--legacy-permissions', choices=['readonly', 'editor', 'unrestricted'], help='Explicit policy for workspaces without a version-2 policy')
    args = parser.parse_args()
    if args.legacy_permissions and not args.activate:
        parser.error('--legacy-permissions requires runtime update')
    ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
    with (ROOT / '.manage.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if (ROOT / 'transaction').exists(): raise RuntimeError('Run titian recover first.')
        stage = build()
        if args.install:
            if (ROOT / 'runtime').exists():
                shutil.rmtree(stage)
                raise RuntimeError('Runtime already exists; use --activate to update it.')
            os.replace(stage, ROOT / 'runtime')
            print('Runtime installed. Use titian add to start a project.')
        elif args.activate: activate(stage, args.legacy_permissions)
        else:
            shutil.rmtree(stage)
            print('Pinned runtime build and syntax checks passed; active runtime unchanged.')


if __name__ == '__main__': main()
