#!/usr/bin/env python3
"""Build a checked, version-pinned runtime, then activate with rollback.
No project registry or credentials are regenerated by setup.
"""
from pathlib import Path
import argparse
import fcntl
import json
import os
import shutil
import subprocess
import tempfile
import time
import manage

ROOT = Path(__file__).resolve().parent
EXPECTED = {'@wonderwhy-er/desktop-commander': '0.2.51', '@modelcontextprotocol/sdk': '1.30.0'}


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError('Unsupported Desktop Commander config layout; runtime not changed.')
    return text.replace(old, new, 1)


def build():
    deps = ROOT / 'dependencies/node_modules'
    for name, version in EXPECTED.items():
        actual = json.loads((deps / name / 'package.json').read_text())['version']
        if actual != version: raise RuntimeError(f'{name}: expected {version}, found {actual}. Run npm ci --prefix dependencies.')
    stage = Path(tempfile.mkdtemp(prefix='.runtime-stage-', dir=ROOT))
    try:
        dc = deps / '@wonderwhy-er/desktop-commander'
        shutil.copytree(dc / 'dist', stage / 'dc/dist')
        shutil.copy2(dc / 'package.json', stage / 'dc/package.json')
        # Node also walks this parent node_modules for hoisted dependencies.
        (stage / 'node_modules').symlink_to(deps, target_is_directory=True)
        if (dc / 'node_modules').exists(): (stage / 'dc/node_modules').symlink_to(dc / 'node_modules', target_is_directory=True)
        config = stage / 'dc/dist/config.js'
        config.write_text(replace_once(config.read_text(), "const CONFIG_DIR = path.join(USER_HOME, '.claude-server-commander');", "const CONFIG_DIR = process.env.MCP_DC_CONFIG_DIR || path.join(USER_HOME, '.claude-server-commander');"))
        (stage / 'bridge').mkdir()
        (stage / 'bridge/package.json').write_text('{"type":"module","private":true}')
        shutil.copy2(ROOT / 'src/bridge.mjs', stage / 'bridge/bridge.js')
        shutil.copy2(ROOT / 'src/auth-proxy.cjs', stage / 'auth-proxy.cjs')
        shutil.copy2(ROOT / 'src/dc-wrapper.cjs', stage / 'dc-wrapper.js')
        for script in ['bridge/bridge.js', 'auth-proxy.cjs', 'dc-wrapper.js', 'dc/dist/config.js']:
            subprocess.run([manage.node_binary(), '--check', str(stage / script)], check=True)
        (stage / 'build.json').write_text(json.dumps(EXPECTED, indent=2))
        return stage
    except Exception:
        shutil.rmtree(stage)
        raise


def activate(stage):
    runtime = ROOT / 'runtime'
    projects = [p for p in manage.load() if p.get('enabled', True)]
    names = [manage.label(p['slug'], part) for p in projects for part in ['bridge', 'auth']]
    running = [name for name in names if manage.loaded(name)]
    backup = ROOT / 'archives' / f'runtime-{time.time_ns()}'
    backup.parent.mkdir(exist_ok=True, mode=0o700)
    swapped = False
    try:
        for name in running: manage.stop(name)
        if runtime.exists(): os.replace(runtime, backup)
        try: os.replace(stage, runtime)
        except Exception:
            if backup.exists(): os.replace(backup, runtime)
            raise
        swapped = True
        for name in running: manage.launch('bootstrap', manage.DOMAIN, str(manage.AGENTS / (name + '.plist')))
        for p in projects:
            if manage.label(p['slug'], 'bridge') in running:
                manage.wait_health(p['bridgePort']); manage.wait_health(p['authPort'])
    except Exception:
        for name in running: manage.stop(name)
        if swapped:
            failed = ROOT / 'archives' / f'runtime-failed-{time.time_ns()}'
            os.replace(runtime, failed)
            if backup.exists(): os.replace(backup, runtime)
        for name in running: manage.launch('bootstrap', manage.DOMAIN, str(manage.AGENTS / (name + '.plist')))
        raise
    print('Runtime activated. Existing credentials and registry preserved.')


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--install', action='store_true', help='Install a first runtime without starting services')
    mode.add_argument('--activate', action='store_true', help='Restart active project services using the checked runtime')
    args = parser.parse_args()
    with (ROOT / '.manage.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if (ROOT / 'transaction').exists(): raise RuntimeError('Run mcp-project recover first.')
        stage = build()
        if args.install:
            if (ROOT / 'runtime').exists():
                shutil.rmtree(stage)
                raise RuntimeError('Runtime already exists; use --activate to update it.')
            os.replace(stage, ROOT / 'runtime')
            print('Runtime installed. Use mcp-project add to start a project.')
        elif args.activate: activate(stage)
        else:
            shutil.rmtree(stage)
            print('Pinned runtime build and syntax checks passed; active runtime unchanged.')


if __name__ == '__main__': main()
